steps:
  # Step 0: Generate dynamic version
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate Version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG="v-$(date +%Y%m%d-%H%M%S)"
        echo "VERSION_TAG=$$VERSION_TAG" > /workspace/version.env
        echo "Generated version: $$VERSION_TAG"

  # Step 1: Check/create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-zip-repo --location=asia-east1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create vamsi-zip-repo --repository-format=generic --location=asia-east1 --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Download ZIP file from GitHub
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download ZIP from GitHub'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Starting download from GitHub..."
        curl -L https://github.com/20481A04K2/cloudbuildzipfile/archive/refs/heads/main.zip -o source.zip
        echo "Download completed"

  # Step 3: Authenticate with Google Cloud
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Authenticate'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Authenticating with Google Cloud..."
        gsutil cp gs://vamsi-artifact-bucket/enhub-cloud-interns-004fbd59b047.json /workspace/key.json
        gcloud auth activate-service-account --key-file=/workspace/key.json
        echo "Authentication successful"

  # Step 4: Show ZIP file size
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Show ZIP File Size'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "The size of the downloaded ZIP file:"
        du -sh source.zip

  # Step 5: Upload ZIP to Artifact Registry with dynamic version
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Upload to Artifact Registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        echo "Uploading ZIP to Artifact Registry with version: $$VERSION_TAG"
        gcloud artifacts generic upload \
          --project="enhub-cloud-interns" \
          --location="asia-east1" \
          --repository="vamsi-zip-repo" \
          --package="source-package" \
          --version="$$VERSION_TAG" \
          --source="source.zip"
        echo "Upload completed"

  # Step 6: Delete VM if it exists
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Delete VM if exists'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking if VM exists..."
        if gcloud compute instances describe my-vm-instance --zone=asia-east1-b --project=enhub-cloud-interns; then
          echo "VM exists. Deleting it now..."
          gcloud compute instances delete my-vm-instance --zone=asia-east1-b --quiet
        else
          echo "VM does not exist. Proceeding to create a new VM."
        fi

  # Step 7: Create a new VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create VM'
    args:
      - compute
      - instances
      - create
      - my-vm-instance
      - --zone=asia-east1-b
      - --machine-type=e2-micro
      - --image-family=debian-11
      - --image-project=debian-cloud
      - --boot-disk-size=10GB
      - --tags=http-server,https-server
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --service-account=1064351983714-compute@developer.gserviceaccount.com
      - --project=enhub-cloud-interns

  # Step 8: Add SSH key to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Add SSH key to VM'
    args:
      - compute
      - instances
      - add-metadata
      - my-vm-instance
      - --zone=asia-east1-b
      - --metadata=ssh-keys="sajja_vamsi:$(cat /workspace/ssh_key.pub)"
      - --project=enhub-cloud-interns

  # Step 9: Copy ZIP file to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy ZIP to VM'
    args:
      - compute
      - scp
      - source.zip
      - sajja_vamsi@my-vm-instance:/home/sajja_vamsi
      - --zone=asia-east1-b
      - --project=enhub-cloud-interns

  # Step 10: SSH into VM, install Flask and run app
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Unzip and Run Flask App'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh sajja_vamsi@my-vm-instance \
          --zone=asia-east1-b \
          --project=enhub-cloud-interns \
          --command="bash -c '
            set -e
            sudo apt-get update
            sudo apt-get install -y unzip python3-pip
            unzip -o /home/sajja_vamsi/source.zip -d /home/sajja_vamsi/my-app
            cd /home/sajja_vamsi/my-app/cloudbuildzipfile-main
            pip3 install --user flask
            echo Starting Flask app...
            nohup python3 app.py > /home/sajja_vamsi/flask.log 2>&1 & 
          '"

  # Step 11: Create Instance Template with Startup Script
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Instance Template'
    args:
      - compute
      - instance-templates
      - create
      - my-template
      - --machine-type=e2-micro
      - --image-family=debian-11
      - --image-project=debian-cloud
      - --metadata=startup-script=|
          #!/bin/bash
          apt-get update
          apt-get install -y unzip python3-pip
          curl -o /tmp/source.zip https://artifactregistry.googleapis.com/v1/projects/enhub-cloud-interns/locations/asia-east1/repositories/vamsi-zip-repo/packages/source-package/versions/$(cat /workspace/version.env | cut -d'=' -f2)/source.zip
          unzip /tmp/source.zip -d /opt/app
          cd /opt/app
          pip3 install flask
          nohup python3 app.py > /var/log/app.log 2>&1 &

  # Step 12: Create Managed Instance Group (MIG)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create MIG'
    args:
      - compute
      - instance-groups
      - managed
      - create
      - my-mig
      - --base-instance-name=my-instance
      - --template=my-template
      - --size=1
      - --zone=asia-east1-b

  # Step 13: Set Autoscaling Policy
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Set Autoscaling'
    args:
      - compute
      - instance-groups
      - managed
      - set-autoscaling
      - my-mig
      - --zone=asia-east1-b
      - --min-num-replicas=1
      - --max-num-replicas=5
      - --target-cpu-utilization=0.01
      - --cool-down-period=60

  # Step 14: Create Health Check (Port 8080)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Health Check'
    args:
      - compute
      - health-checks
      - create
      - http
      - my-health-check
      - --port=8080

  # Step 15: Create Backend Service
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Backend Service'
    args:
      - compute
      - backend-services
      - create
      - my-backend-service
      - --protocol=HTTP
      - --port-name=http
      - --health-checks=my-health-check
      - --global

  # Step 16: Add MIG to Backend Service
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Add Backend'
    args:
      - compute
      - backend-services
      - add-backend
      - my-backend-service
      - --instance-group=my-mig
      - --instance-group-zone=asia-east1-b
      - --global

  # Step 17: Create URL Map
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create URL Map'
    args:
      - compute
      - url-maps
      - create
      - my-url-map
      - --default-service=my-backend-service

  # Step 18: Create Target HTTP Proxy
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create HTTP Proxy'
    args:
      - compute
      - target-http-proxies
      - create
      - my-http-proxy
      - --url-map=my-url-map

  # Step 19: Create Global Forwarding Rule
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Forwarding Rule'
    args:
      - compute
      - forwarding-rules
      - create
      - my-forwarding-rule
      - --global
      - --target-http-proxy=my-http-proxy
      - --ports=8080
