steps:
  # Step 0: Generate dynamic version tag
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate Version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG="v-$(date +%Y%m%d-%H%M%S)"
        echo "VERSION_TAG=$$VERSION_TAG" > /workspace/version.env
        echo "Generated version: $$VERSION_TAG"

  # Step 1: Check or create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-zip-repo --location=asia-east1 --project=enhub-cloud-interns; then
          gcloud artifacts repositories create vamsi-zip-repo \
            --repository-format=generic \
            --location=asia-east1 \
            --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Download ZIP from GitHub
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download ZIP from GitHub'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        curl -L https://github.com/20481A04K2/cloudbuildzipfile/archive/refs/heads/main.zip -o source.zip

  # Step 3: Authenticate service account
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Authenticate'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        gsutil cp gs://vamsi-artifact-bucket/enhub-cloud-interns-004fbd59b047.json /workspace/key.json
        gcloud auth activate-service-account --key-file=/workspace/key.json

  # Step 4: Show file size
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Show ZIP Size'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        du -sh source.zip

  # Step 5: Upload to Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Upload ZIP'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        echo "Uploading source.zip as version $$VERSION_TAG"
        gcloud artifacts generic upload \
          --project="enhub-cloud-interns" \
          --location="asia-east1" \
          --repository="vamsi-zip-repo" \
          --package="source-package" \
          --version="$$VERSION_TAG" \
          --source="source.zip"

  # Step 6: Create a new versioned instance template
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Instance Template'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        gcloud compute instance-templates create vamsi-template-$$VERSION_TAG \
          --machine-type=e2-micro \
          --tags=allow-8080 \
          --region=asia-east1 \
          --metadata=startup-script='#! /bin/bash
            apt-get update
            apt-get install -y unzip python3-pip curl
            curl -o /home/sajja_vamsi/source.zip https://artifactregistry.googleapis.com/v1/projects/enhub-cloud-interns/locations/asia-east1/repositories/vamsi-zip-repo/packages/source-package/versions/'"$$VERSION_TAG"'/source.zip
            unzip -o /home/sajja_vamsi/source.zip -d /home/sajja_vamsi/my-app
            cd /home/sajja_vamsi/my-app/cloudbuildzipfile-main
            pip3 install flask
            nohup python3 app.py > /home/sajja_vamsi/flask.log 2>&1 &'

  # Step 7: Create or Update MIG
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create or Update MIG'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        MIG_NAME="vamsi-mig"
        # Fetch version tag
        source /workspace/version.env
        echo "Using version tag: $$VERSION_TAG"
        
        # Ensure health check exists before creating MIG
        if ! gcloud compute health-checks describe vamsi-health-check --region=asia-east1 > /dev/null 2>&1; then
          echo "Health check does not exist, creating it..."
          gcloud compute health-checks create http vamsi-health-check \
            --region=asia-east1 \
            --port=8080 \
            --request-path="/" \
            --check-interval=5s \
            --timeout=5s \
            --healthy-threshold=2 \
            --unhealthy-threshold=2 \
            --project=enhub-cloud-interns
        else
          echo "Health check already exists."
        fi
        
        # Check if MIG exists
        if gcloud compute instance-groups managed describe $$MIG_NAME --region=asia-east1 > /dev/null 2>&1; then
          echo "MIG $$MIG_NAME exists, updating it..."
          gcloud compute instance-groups managed set-instance-template $$MIG_NAME \
            --template=vamsi-template-$$VERSION_TAG \
            --zone=asia-east1-b
        else
          echo "MIG $$MIG_NAME does not exist, creating it..."
          if [ -z "$$VERSION_TAG" ]; then
            echo "ERROR: VERSION_TAG is empty!"
            exit 1
          fi
          # Create MIG with health check
          gcloud compute instance-groups managed create $$MIG_NAME \
            --template=vamsi-template-$$VERSION_TAG \
            --zone=asia-east1-b \
            --size=1 \
            --health-check=vamsi-health-check \
            --initial-delay=60s \
            --project=enhub-cloud-interns
        fi

  # Step 8: Create firewall rule if not exists
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Firewall'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud compute firewall-rules describe allow-8080 --project=enhub-cloud-interns > /dev/null 2>&1; then
          gcloud compute firewall-rules create allow-8080 \
            --allow tcp:8080 \
            --target-tags=allow-8080 \
            --direction=INGRESS \
            --priority=1000 \
            --project=enhub-cloud-interns
        else
          echo "Firewall rule already exists"
        fi

  # Step 9: Create Health Check (fix path)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Health Check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud compute health-checks describe vamsi-health-check --region=asia-east1 > /dev/null 2>&1; then
          gcloud compute health-checks create http vamsi-health-check \
            --region=asia-east1 \
            --port=8080 \
            --request-path="/" \
            --check-interval=5s \
            --timeout=5s \
            --healthy-threshold=2 \
            --unhealthy-threshold=2 \
            --project=enhub-cloud-interns
        else
          echo "Health check already exists"
        fi

  # Step 10: Enable Autohealing for MIG
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Autohealing'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        gcloud compute instance-groups managed update vamsi-mig \
          --region=asia-east1 \
          --health-check=vamsi-health-check \
          --initial-delay=60s \
          --project=enhub-cloud-interns

  # Step 11: Enable autoscaling based on CPU utilization
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Enable Autoscaling'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        gcloud compute instance-groups managed set-autoscaling vamsi-mig \
          --zone=asia-east1-b \
          --min-num-replicas=1 \
          --max-num-replicas=5 \
          --target-cpu-utilization=0.01 \
          --cool-down-period=60s \
          --project=enhub-cloud-interns

  # Step 12: Create Load Balancer
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Load Balancer'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        gcloud compute forwarding-rules create vamsi-lb-rule \
          --region=asia-east1 \
          --ports=8080 \
          --address=0.0.0.0 \
          --target-pool=vamsi-lb-pool \
          --project=enhub-cloud-interns

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
