steps:
  # Step 0: Generate dynamic version
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate Version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG="v-$(date +%Y%m%d-%H%M%S)"
        echo "VERSION_TAG=$VERSION_TAG" > /workspace/version.env
        echo "Generated version: $VERSION_TAG"

  # Step 1: Check/create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-zip-repo --location=asia-east1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create vamsi-zip-repo --repository-format=generic --location=asia-east1 --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Download ZIP file from GitHub
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download ZIP from GitHub'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Starting download from GitHub..."
        curl -L https://github.com/20481A04K2/cloudbuildzipfile/archive/refs/heads/main.zip -o source.zip
        echo "Download completed"

  # Step 3: Authenticate with Google Cloud
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Authenticate'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Authenticating with Google Cloud..."
        gsutil cp gs://vamsi-artifact-bucket/enhub-cloud-interns-004fbd59b047.json /workspace/key.json
        gcloud auth activate-service-account --key-file=/workspace/key.json
        echo "Authentication successful"

  # Step 4: Show ZIP file size
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Show ZIP File Size'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "The size of the downloaded ZIP file:"
        du -sh source.zip

  # Step 5: Upload ZIP to Artifact Registry with dynamic version
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Upload to Artifact Registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        echo "Uploading ZIP to Artifact Registry with version: $VERSION_TAG"
        gcloud artifacts generic upload \
          --project="enhub-cloud-interns" \
          --location="asia-east1" \
          --repository="vamsi-zip-repo" \
          --package="source-package" \
          --version="$VERSION_TAG" \
          --source="source.zip"
        echo "Upload completed"

  # Step 6: Create Instance Template with Startup Script
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Instance Template'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG=$(cat /workspace/version.env | cut -d'=' -f2)
        gcloud compute instance-templates create my-template \
          --machine-type=e2-micro \
          --image-family=debian-11 \
          --image-project=debian-cloud \
          --metadata=startup-script='#!/bin/bash
            set -e
            sudo apt-get update
            sudo apt-get install -y unzip python3-pip
            curl -o /home/sajja_vamsi/source.zip "https://artifactregistry.googleapis.com/v1/projects/enhub-cloud-interns/locations/asia-east1/repositories/vamsi-zip-repo/packages/source-package/versions/'$VERSION_TAG'/source.zip"
            mkdir -p /home/sajja_vamsi/my-app
            unzip -o /home/sajja_vamsi/source.zip -d /home/sajja_vamsi/my-app
            cd /home/sajja_vamsi/my-app/cloudbuildzipfile-main
            pip3 install --user flask
            echo Starting Flask app...
            nohup python3 app.py > /home/sajja_vamsi/flask.log 2>&1 &'

  # Step 7: Create Managed Instance Group (MIG)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create MIG'
    args:
      - compute
      - instance-groups
      - managed
      - create
      - my-mig
      - --base-instance-name=my-instance
      - --template=my-template
      - --size=1
      - --zone=asia-east1-b

  # Step 8: Set Autoscaling for MIG
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Set Autoscaling'
    args:
      - compute
      - autoscaler
      - create
      - my-mig-autoscaler
      - --zone=asia-east1-b
      - --target=https://www.googleapis.com/compute/v1/projects/enhub-cloud-interns/zones/asia-east1-b/instanceGroupManagers/my-mig
      - --cool-down-period=60
      - --min-num-replicas=1
      - --max-num-replicas=10
      - --target-cpu-utilization=0.01

options:
  logging: CLOUD_LOGGING_ONLY
